export const SET_MAPPING = 'SET_MAPPING'
export const REMOVE_MAPPING = 'REMOVE_MAPPING'

export const FETCH_POSTS='FETCH_POSTS'
export const CREATE_POST='CREATE_POST'
export const UPDATE_POST='UPDATE_POST'
